### ISSUE TITLE
Not adding Award content

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Geography-and-Urban-Studies#1]
I am not adding the Undergraduate Department Award page, it is a wall of words and the past recipients can be found under awards on libarts.temple.edu.

**Comment by tu-chill** [comment]
@zepstein Does the copy on program pages mention or link to the awards content on liberalarts.temple.edu? is this content that we need for all, some, or none, of the programs?

**Comment by zepstein** [comment]
It doesn’t, I don’t think it needs to.

--
Zach Epstein
Director, Marketing and Communications
College of Liberal Arts
Temple University

1114 W. Berks St. | 835 Anderson Hall
Philadelphia, PA 19122
215-204-6243
zepstein@temple.edu<mailto:zepstein@temple.edu>

On Mar 17, 2017, at 10:04 AM, Christopher Hill <notifications@github.com<mailto:notifications@github.com>> wrote:


@zepstein<https://github.com/zepstein> Does the copy on program pages mention or link to the awards content on liberalarts.temple.edu<http://liberalarts.temple.edu>? is this content that we need for all, some, or none, of the programs?

**Comment by tu-chill** [comment]
noted
