### ISSUE TITLE
300 Word Faculty Introduction

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Geography-and-Urban-Studies#5]
All faculty pages need a program specific 300 word description at the top of the page.

**Comment by saracurnow** [comment]
Roger. Will add these to my list. Thanks!

**Comment by CVE82** [comment]
You got it, thanks so much! Just adding the issue to all of the the sites, already live and upcoming.

**Comment by saracurnow** [comment]
Sounds great. Will help me keep track.

**Comment by CVE82** [comment]
Super! This is my "Go Live Checklist" that Chris and I use, you can use it too to help keep yourself track!

[Go Live Website Checklist.xlsx](https://github.com/TULiberalArts/Geography-and-Urban-Studies/files/1095807/Go.Live.Website.Checklist.xlsx)

**Comment by saracurnow** [comment]
Awesome thanks!

**Comment by saracurnow** [comment]
Checking to see if the one I added looks good to everyone before I close this.

**Comment by CVE82** [comment]
It looks great thank you! The research link just needs to be redirected...
