### ISSUE TITLE
Hero image needed

### ISSUE THREAD

**Issue by saracurnow** [TULiberalArts/Geography-and-Urban-Studies#6]

**Comment by ZMcGroarty** [comment]
Hey,

Uploading images. For some wacky reason my photoshop won't export PNGs right now. I'll loop back around and fix these when it decides to again, but it can at least go to faculty review

![hero_gus](https://user-images.githubusercontent.com/15017242/29974884-61a2c43a-8f02-11e7-85bd-e4fc02450146.jpg)
